### PR TITLE
feat: support preferredDatePickerStyle in iOS 14

### LINKED ISSUE #75: Include the day of the week in "date" mode
Thanks for maintaining this repo!

What I'd like is to include the day of the week (e.g., Mon/, Tues.) in "date" mode for iOS. I understand that for iOS it's possible to get the day of the week in "datetime" mode - what I'm looking for is just the day of the week and the date. Android doesn't have the same issue because it shows the entire calendar with day of the week abbreviations at the top.

For example, it would make it easier for the user to understand the date they're choosing based on whether it's a weekday or weekend day.

I searched for and couldn't find a way to override the labels. If helpful I'd be happy to contribute a PR if maintainers have a good idea on the best implementation. 

Thanks again!

### LINKED ISSUE #203: Compiling against the iOS 14 SDK changes the look of the native APIs, so this library looks extremely weird.
# Bug report

## Summary

Compiling against the iOS 14 SDK changes the look of the native APIs, so this library looks extremely weird. Namely, the pickers have way too much spacing surrounding them.

Library version: 2.4.2

Using the example app to demonstrate, they look like this:

ezgif com-video-to-gif

An example of both natively used is in the Calendar app:
IMG_D21D4E6D455A-1

### PR DESCRIPTION
**Pull request by vonovak**
# Summary

The PR was opened by @SConaway in #211, who raised the issue about weird appearance in ios 14. @vonovak took over most of the implementation. This PR was opened just to trigger automatic release (that was not handled before due to wrong format of commit message).

This adds support for [preferredDatePickerStyle](https://developer.apple.com/documentation/uikit/uidatepicker/3526124-preferreddatepickerstyle?changes=latest_minor&language=objc) to the module. I took the android-only `display` prop and extended the support for ios too, as opposed to adding a new ios-only prop.

The implementation was quite involved; for display: `spinner, compact and inline` we just assign those to `preferredDatePickerStyle` but for `default` we first need to find out what that is going to be, which is determined by the OS, and hence there is a async call across the bridge to find this out. The value could be cached I suppose, but that can be done later.

I also refactored the example app so that all the possible combinations can be properly tested. That also means changing e2e tests 😅 

this requires xcode 11 to build, so we'll make this a breaking change

This closes #203, closes #75

## Test Plan

Build and test the example app on xcode 11 and xcode 12

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by scarlac** [comment]
Thanks @vonovak ! Much appreciated. 

FYI: A coworker had an issue where an `@available` rule wouldn't prevent Xcode from checking the block where we were manually setting the preferred style ourselves. He was running Xcode 11.2. It seemed to work on another machine with Xcode 11.4. Despite Apple's docs saying version Xcode >=11.0. Just in case someone reports compilation issues.

**Comment by abdo17rabah** [comment]
How can i please update the package to use `display= "spiner"`

**Comment by SConaway** [comment]
@abdo17rabah 

Assuming you're on the latest version (3.0.8 as of now), set that prop on the component you're rendering (either in a class's `render()` or a function's `return`) like this: `<RNDateTimePicker display="spinner" value={date} onChange={setDate} />`. Is this what you mean?

CleanShot 2020-12-16 at 08 19 16@2x

**Pull request merged**
