### PR TITLE
Android `minuteInterval` prop support

### PR DESCRIPTION
**Pull request by e1ferapontov**
# Summary

As we know, `minuteInterval` is only available for iOS now, and that's a feature many people desire to have on Android as well. These changes bring at least partial support of `minuteInterval` prop for Android.

Right now I've only covered 5 min increments of `minuteInverval` prop (mostly because I've only needed them for my work), but all the rest of iOS-only values should work nicely for `spinner` TimePicker mode with no or little changes.

## Test Plan
I've added additional `detox` test cases for this functionality.

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by luancurti** [comment]
@e1ferapontov Could you rebase onto branch master?

**Comment by e1ferapontov** [comment]
Sorry I was pretty busy past months, I'll update pull request asap

**Comment by lucasklaassen** [comment]
@e1ferapontov thank you for taking the time to build this. Very useful! :)

**Comment by lucasklaassen** [comment]
I'm having trouble building the android project within this branch.

Command I ran:
```
npm run start:android
```

```
Execution failed for task ':react-native-datetimepicker:compileDebugJavaWithJavac'.
```

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:23: error: package javafx.scene.control does not exist
import javafx.scene.control.Dialog;
                           ^
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:37: error: cannot find symbol
  public Dialog onCreateDialog(Bundle savedInstanceState) {
         ^
  symbol:   class Dialog
  location: class RNTimePickerDialogFragment
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:50: error: cannot find symbol
          Context activityContext,
          ^
  symbol:   class Context
  location: class RNTimePickerDialogFragment
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:111: error: cannot find symbol
          Bundle args, Context activityContext,
                       ^
  symbol:   class Context
  location: class RNTimePickerDialogFragment
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:19: error: package javax.swing.text does not exist
import javax.swing.text.View;
                       ^
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:28: error: a type with the same simple name is already defined by the single-type-import of Nullable
import androidx.annotation.Nullable;
^
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:29: error: package sun.rmi.runtime does not exist
import sun.rmi.runtime.Log;
                      ^
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:51: error: cannot find symbol
  private Handler handler = new Handler();
          ^
  symbol:   class Handler
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:61: error: cannot find symbol
    Context context,
    ^
  symbol:   class Context
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:76: error: cannot find symbol
    Context context,
    ^
  symbol:   class Context
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:258: error: cannot find symbol
    Context context,
    ^
  symbol:   class Context
  location: class RNDismissableTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:271: error: cannot find symbol
    Context context,
    ^
  symbol:   class Context
  location: class RNDismissableTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:285: error: cannot find symbol
      Context context,
      ^
  symbol:   class Context
  location: class RNDismissableTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:302: error: cannot find symbol
  private void fixSpinner(Context context, int hourOfDay, int minute, boolean is24HourView) {
                          ^
  symbol:   class Context
  location: class RNDismissableTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:32: error: a type with the same simple name is already defined by the single-type-import of Nullable
import androidx.annotation.Nullable;
^
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:51: error: cannot find symbol
  private Handler handler = new Handler();
                                ^
  symbol:   class Handler
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:54: error: cannot find symbol
  private final int textInputPickerID = Resources.getSystem()
                                        ^
  symbol:   variable Resources
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:57: error: cannot find symbol
  private final int timePickerId = Resources.getSystem()
                                   ^
  symbol:   variable Resources
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:134: error: cannot find symbol
    final View textInputPicker = this.findViewById(textInputPickerID);
          ^
  symbol:   class View
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:191: error: cannot find symbol
    Log.d(LOG_TAG, "onClick" + which);
    ^
  symbol:   variable Log
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:231: error: cannot find symbol
        int minutePickerId = Resources.getSystem()
                             ^
  symbol:   variable Resources
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:248: error: cannot find symbol
      Log.e(LOG_TAG, "onAttachedToWindow encountered an error:");
      ^
  symbol:   variable Log
  location: class CustomTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:326: error: cannot find symbol
            Constructor spinnerDelegateConstructor = spinnerDelegateClass.getConstructor(TimePicker.class, Context.class, AttributeSet.class, int.class, int.class);
                                                                                                           ^
  symbol:   class Context
  location: class RNDismissableTimePickerDialog
/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:326: error: cannot find symbol
            Constructor spinnerDelegateConstructor = spinnerDelegateClass.getConstructor(TimePicker.class, Context.class, AttributeSet.class, int.class, int.class);
                                                                                                                          ^
  symbol:   class AttributeSet
  location: class RNDismissableTimePickerDialog
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
24 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-datetimepicker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:600:11)
    at execFileSync (child_process.js:618:13)
    at runOnAllDevices (/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mrk13n** [comment]
> I'm having trouble building the android project within this branch.
> 
> Command I ran:
> 
> ```
> npm run start:android
> ```
> 
> ```
> Execution failed for task ':react-native-datetimepicker:compileDebugJavaWithJavac'.
> ```
> 
> ```
> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:23: error: package javafx.scene.control does not exist
> import javafx.scene.control.Dialog;
>                            ^
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:37: error: cannot find symbol
>   public Dialog onCreateDialog(Bundle savedInstanceState) {
>          ^
>   symbol:   class Dialog
>   location: class RNTimePickerDialogFragment
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:50: error: cannot find symbol
>           Context activityContext,
>           ^
>   symbol:   class Context
>   location: class RNTimePickerDialogFragment
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:111: error: cannot find symbol
>           Bundle args, Context activityContext,
>                        ^
>   symbol:   class Context
>   location: class RNTimePickerDialogFragment
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:19: error: package javax.swing.text does not exist
> import javax.swing.text.View;
>                        ^
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:28: error: a type with the same simple name is already defined by the single-type-import of Nullable
> import androidx.annotation.Nullable;
> ^
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:29: error: package sun.rmi.runtime does not exist
> import sun.rmi.runtime.Log;
>                       ^
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:51: error: cannot find symbol
>   private Handler handler = new Handler();
>           ^
>   symbol:   class Handler
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:61: error: cannot find symbol
>     Context context,
>     ^
>   symbol:   class Context
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:76: error: cannot find symbol
>     Context context,
>     ^
>   symbol:   class Context
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:258: error: cannot find symbol
>     Context context,
>     ^
>   symbol:   class Context
>   location: class RNDismissableTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:271: error: cannot find symbol
>     Context context,
>     ^
>   symbol:   class Context
>   location: class RNDismissableTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:285: error: cannot find symbol
>       Context context,
>       ^
>   symbol:   class Context
>   location: class RNDismissableTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:302: error: cannot find symbol
>   private void fixSpinner(Context context, int hourOfDay, int minute, boolean is24HourView) {
>                           ^
>   symbol:   class Context
>   location: class RNDismissableTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:32: error: a type with the same simple name is already defined by the single-type-import of Nullable
> import androidx.annotation.Nullable;
> ^
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:51: error: cannot find symbol
>   private Handler handler = new Handler();
>                                 ^
>   symbol:   class Handler
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:54: error: cannot find symbol
>   private final int textInputPickerID = Resources.getSystem()
>                                         ^
>   symbol:   variable Resources
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:57: error: cannot find symbol
>   private final int timePickerId = Resources.getSystem()
>                                    ^
>   symbol:   variable Resources
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:134: error: cannot find symbol
>     final View textInputPicker = this.findViewById(textInputPickerID);
>           ^
>   symbol:   class View
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:191: error: cannot find symbol
>     Log.d(LOG_TAG, "onClick" + which);
>     ^
>   symbol:   variable Log
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:231: error: cannot find symbol
>         int minutePickerId = Resources.getSystem()
>                              ^
>   symbol:   variable Resources
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:248: error: cannot find symbol
>       Log.e(LOG_TAG, "onAttachedToWindow encountered an error:");
>       ^
>   symbol:   variable Log
>   location: class CustomTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:326: error: cannot find symbol
>             Constructor spinnerDelegateConstructor = spinnerDelegateClass.getConstructor(TimePicker.class, Context.class, AttributeSet.class, int.class, int.class);
>                                                                                                            ^
>   symbol:   class Context
>   location: class RNDismissableTimePickerDialog
> /Users/lucasklaassen/Documents/programming/react-native-datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java:326: error: cannot find symbol
>             Constructor spinnerDelegateConstructor = spinnerDelegateClass.getConstructor(TimePicker.class, Context.class, AttributeSet.class, int.class, int.class);
>                                                                                                                           ^
>   symbol:   class AttributeSet
>   location: class RNDismissableTimePickerDialog
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 24 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-datetimepicker:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> 
>     at checkExecSyncError (child_process.js:600:11)
>     at execFileSync (child_process.js:618:13)
>     at runOnAllDevices (/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
>     at buildAndRun (/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
>     at then.result (/Users/lucasklaassen/Documents/programming/react-native-datetimepicker/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> ```

same problem:(

**Comment by MartinArnautov** [comment]
So, when is a new version with minuteInterval of android released?

**Comment by zakmysta** [comment]
+1 for this feature. My use case requires choosing half hour intervals, so I've set the `minuteInterval` to `30` for iOS. For Android, I've added some code to round the returned value to the nearest half hour interval. Looking forward to having this functionality natively!

**Comment by akondo06** [comment]
Any chance this will make it?

**Pull request closed without merging**
